Changed markup when using optgroup element
mysociety/jquery-multi-select pull request #42
Opened 2024-01-15 14:24 UTC by lucascumsille

Instead of using the pseudo element to display the title of a optgroup, now they will be wrapped on a fieldset with a legend. The legend will have the text from the label atrribute from the optgroup.

It's also possible to change the class names for the fieldset and legend, by using these settings: menuFieldsetHTML and menuFieldsetLegendHTML.

<img width="339" alt="Screenshot 2024-01-15 at 14 10 36" src="https://github.com/mysociety/jquery-multi-select/assets/13790153/03b43dc2-ec62-452e-bed3-8d3c458086e6">

2024-01-16 09:09 UTC, dracos requested changes
Some suggestions, let me know what you think. Also as mentioned elsewhere we'll need to make the up/down changes here (in e.g. the upDown function).

2024-01-16 09:09 UTC, dracos commented on demo/index.html
> +            menuItemHTML: $('<label class="multi-select-menuitem test">'),
Presumably this change not needed :)

2024-01-16 09:09 UTC, dracos commented on src/jquery.multi-select.min.js
This file has disappeared

2024-01-16 09:09 UTC, dracos commented on src/example-styles.css
> +legend {
The rest of the file only uses class names, probably good to stick with that, and use `.multi-select-legend` here?

2024-01-16 09:09 UTC, dracos commented on src/example-styles.css
> +    padding-top: 0.25rem;
Dunno if this is just me used to the old one, but this felt a bit spaced out to me now, especially if there's going to be a lot of options? What do you think about dropping this padding-top and adding a:
`.multi-select-legend + .multi-select-menuitem { padding-top: 0.25rem; }`
to reduce the spacing a bit?

2024-01-16 09:09 UTC, dracos commented on src/jquery.multi-select.js
> +      console.log($fieldset);
will need removing

2024-01-22 16:28 UTC, dracos commented
@lucascumsille I've pushed a commit that hopefully gets up/down working as before if you'd like to take a look. I've also fixed the tests.

2024-01-23 08:44 UTC, lucascumsille commented
@dracos That's perfect is working for me. I tried it on Voiceover, and it works slightly different than the one we used to have, where on each option it would read = "Group title + option name" Example "Flavour Vanilla", now it gives the name of the group when you are in the first option of the group, which is exactly what happens with GOVUK and by default.

If we wanted to keep the current behaviour we could include an `aria-label` that reads "Flavour Vanilla", but I'm not sure if it's unnecessary, because screenreader users are already used to the default. At the same time I liked the fact that "Flavour Vanilla" provides context without the need of having good memory, but it can be a pain with long lists or fieldsets with long names.

Let me know what you think, otherwise I can just merge to master.

2024-01-23 09:16 UTC, dracos commented
I think going with the default fieldset behaviour is probably more consistent, yeah - the category list on FMS map filter can be quite long, but OTOH will have a few fieldsets in it, but hopefully will be clear.

2024-01-23 09:20 UTC, lucascumsille commented
@dracos Sounds good, let's keep it like that. Should I merge it master?

2024-01-23 09:26 UTC, dracos commented
yeah, go for it, up to you if you want to merge the two commits as one or keep it as it is

2024-01-23 09:30 UTC, merged